### ISSUE TITLE
Valor vazio no input 'Time'

### ISSUE THREAD

**Issue by thyagodias** [lukinco/timerlab#10]
Quando o valor do input é apagado o timer apresenta esse resultado:

![Captura de tela de 2020-08-29 12-02-06](https://user-images.githubusercontent.com/31782296/91641001-908f7e00-e9ef-11ea-860f-15786fe4a0ce.png)

Acredito que um diálogo de valor do timer inválido seria uma solução, junto com uma validação no campo

**Comment by vmarcosp** [comment]
Opa, fala @thyagodias! Agradeço por reportar, em breve vamos trabalhar em melhorias e correções de erros como este 😄

**Comment by LuizGMiranda** [comment]
Fiz o teste hoje, e o erro não ocorre mais.

![image](https://user-images.githubusercontent.com/14189420/93892732-3b2f4f80-fcc3-11ea-9c7f-87b04362f9e6.png)

**Comment by thyagodias** [comment]
> Fiz o teste hoje, e o erro não ocorre mais.
> 
> ![image](https://user-images.githubusercontent.com/14189420/93892732-3b2f4f80-fcc3-11ea-9c7f-87b04362f9e6.png)

Falta o click no play, aí deve aparecer como na imagem da issue

**Comment by thyagodias** [comment]
![Peek 22-09-2020 13-42](https://user-images.githubusercontent.com/31782296/93917886-9409e280-fcd9-11ea-9cd5-8ea1ffea3775.gif)

Acredito que faltou você clicar no play pra conseguir reproduzir

**Comment by micalevisk** [comment]
Creio que isso foi corrigido no commit 29479e25217fc1fed35fe5bb0cea730a0fef6c16
